# Generated by Django 4.1.3 on 2022-11-10 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('SSN', models.IntegerField(unique=True)),
                ('birthday', models.DateField()),
                ('phone_number', models.IntegerField(unique=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=11)),
                ('total_commissions', models.DecimalField(decimal_places=2, max_digits=11)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiclemanagement.employee')),
            ],
        ),
    ]
