# Generated by Django 4.1.3 on 2022-11-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanagement', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
