# Generated by Django 4.1.3 on 2022-11-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanagement', '0004_vehicle_image_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
