# Generated by Django 4.1.3 on 2022-11-15 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanagement', '0005_alter_vehicle_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemodel',
            old_name='vehilce_type',
            new_name='vehicle_type',
        ),
    ]
