# Generated by Django 4.1.3 on 2022-11-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanagement', '0006_rename_vehilce_type_vehiclemodel_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='trunk_area',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='number_of_axles',
        ),
        migrations.AddField(
            model_name='car',
            name='max_speed',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='no_of_seats',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='towing_capacity',
            field=models.IntegerField(null=True),
        ),
    ]
