# Generated by Django 4.1.3 on 2022-11-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanagement', '0007_remove_car_trunk_area_remove_truck_number_of_axles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesale',
            name='sale_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
